services:
  product-page:
    image: g37/product-page
    container_name: g37-product-page
    ports: 
      - "9080:9080"
    environment:
      - GROUP_NUMBER=37

  details:
    image: g37/details
    container_name: g37-details
    ports: 
      - "9081:9080"
    depends_on: 
      - product-page

  reviews:
    image: g37/reviews:v3
    container_name: g37-reviews
    depends_on: 
      - product-page

  ratings:
    image: g37/ratings
    container_name: g37-ratings
    ports: 
      - "9082:9080"
    depends_on: 
      - reviews
