FROM node:12.18.1-slim
WORKDIR /opt/microservices/
COPY  bookinfo/src/ratings/ratings.js /opt/microservices/
COPY  bookinfo/src/ratings/package.json /opt/microservices/
ENV SERVICE_VERSION v1
EXPOSE 9080
RUN npm install


CMD ["node","ratings.js","9080"]