version: '3.3'
services:
  productpage:
    build:
      context: .
      dockerfile: Dockerfile-Productpage
    image: 37/productpage
    restart: always
    ports: 
     - 9080:9080
    links:
      - details
      - reviews
  
  details:
    build:
      context: .
      dockerfile: Dockerfile-Details
    image: 37/details
    restart: always
    expose: 
     - 9080
  
  reviews:
    build:
      context: .
      dockerfile: Dockerfile-Reviews
     
    environment: 
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=false
      - STAR_COLOR=black
    image: 37/reviews
    restart: always
    expose: 
     - 9080
    links:
      - ratings
  
  ratings:
    build:
      context: .
      dockerfile: Dockerfile-Ratings
    image: 37/ratings
    restart: always
    expose: 
     - 9080