FROM python:3.7.7-slim

EXPOSE 9080

ENV GROUP_NUMBER=$GROUP_NUMBER

RUN apt-get update \
    && apt-get install -y git
RUN git clone https://github.com/CDPS-ETSIT/practica_creativa2.git
RUN apt-get update
RUN apt-get install -y python3-pip

WORKDIR practica_creativa2/bookinfo/src/productpage/templates

RUN pip3 install -r requirements.txt

CMD sed -i "s/Simple\sBookstore\sApp/Simple Bookstore App - GRUPO ${GROUP_NUMBER}/g" index.html; \
    sed -i "s/Simple\sBookstore\sApp/Simple Bookstore App - GRUPO ${GROUP_NUMBER}/g" productpage.html; \
    python3 /practica_creativa2/bookinfo/src/productpage/productpage.py 9080
